language : node_js

node_js: 12.4.0

cache:
  directories:
    -node_modules

install:
  -npm ci

script:
  -npm test

after_success:
- npm run coverage

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  on:
    branch: develop

